// Generated by SpatialOS codegen. DO NOT EDIT!
// source: improbable.test_schema.BlittableComponentData in blittable_types.schema.

namespace Improbable.TestSchema
{

public partial struct BlittableComponentData : global::System.IEquatable<BlittableComponentData>, global::Improbable.Collections.IDeepCopyable<BlittableComponentData>
{
  /// <summary>
  /// Field bool_field = 1.
  /// </summary>
  public bool boolField;
  /// <summary>
  /// Field int_field = 2.
  /// </summary>
  public int intField;
  /// <summary>
  /// Field long_field = 3.
  /// </summary>
  public long longField;
  /// <summary>
  /// Field float_field = 4.
  /// </summary>
  public float floatField;
  /// <summary>
  /// Field double_field = 5.
  /// </summary>
  public double doubleField;

  public BlittableComponentData(
      bool boolField,
      int intField,
      long longField,
      float floatField,
      double doubleField)
  {
    this.boolField = boolField;
    this.intField = intField;
    this.longField = longField;
    this.floatField = floatField;
    this.doubleField = doubleField;
  }

  public static BlittableComponentData Create()
  {
    var _result = new BlittableComponentData();
    return _result;
  }

  public BlittableComponentData DeepCopy()
  {
    var _result = new BlittableComponentData();
    _result.boolField = boolField;
    _result.intField = intField;
    _result.longField = longField;
    _result.floatField = floatField;
    _result.doubleField = doubleField;
    return _result;

  }

  public override bool Equals(object _obj)
  {
    return _obj is BlittableComponentData && Equals((BlittableComponentData) _obj);
  }

  public static bool operator==(BlittableComponentData a, BlittableComponentData b)
  {
    return a.Equals(b);
  }

  public static bool operator!=(BlittableComponentData a, BlittableComponentData b)
  {
    return !a.Equals(b);
  }

  public bool Equals(BlittableComponentData _obj)
  {
    return
        boolField == _obj.boolField &&
        intField == _obj.intField &&
        longField == _obj.longField &&
        floatField == _obj.floatField &&
        doubleField == _obj.doubleField;
  }

  public override int GetHashCode()
  {
    int _result = 1327;
    _result = (_result * 977) + boolField.GetHashCode();
    _result = (_result * 977) + intField.GetHashCode();
    _result = (_result * 977) + longField.GetHashCode();
    _result = (_result * 977) + floatField.GetHashCode();
    _result = (_result * 977) + doubleField.GetHashCode();
    return _result;
  }
}

public static class BlittableComponentData_Internal
{
  public static unsafe void Write(global::Improbable.Worker.Internal.GcHandlePool _pool,
                                  BlittableComponentData _data, global::Improbable.Worker.Internal.Pbio.Object* _obj)
  {
    {
      global::Improbable.Worker.Internal.Pbio.AddBool(_obj, 1, (byte) (_data.boolField ? 1 : 0));
    }
    {
      global::Improbable.Worker.Internal.Pbio.AddInt32(_obj, 2, _data.intField);
    }
    {
      global::Improbable.Worker.Internal.Pbio.AddInt64(_obj, 3, _data.longField);
    }
    {
      global::Improbable.Worker.Internal.Pbio.AddFloat(_obj, 4, _data.floatField);
    }
    {
      global::Improbable.Worker.Internal.Pbio.AddDouble(_obj, 5, _data.doubleField);
    }
  }

  public static unsafe BlittableComponentData Read(global::Improbable.Worker.Internal.Pbio.Object* _obj)
  {
    BlittableComponentData _data;
    {
      _data.boolField = global::Improbable.Worker.Internal.Pbio.GetBool(_obj, 1) != 0;
    }
    {
      _data.intField = global::Improbable.Worker.Internal.Pbio.GetInt32(_obj, 2);
    }
    {
      _data.longField = global::Improbable.Worker.Internal.Pbio.GetInt64(_obj, 3);
    }
    {
      _data.floatField = global::Improbable.Worker.Internal.Pbio.GetFloat(_obj, 4);
    }
    {
      _data.doubleField = global::Improbable.Worker.Internal.Pbio.GetDouble(_obj, 5);
    }
    return _data;
  }
}

}
