#!/usr/bin/env bash
echo 
echo " ============================================"
echo "    Don't forget to lint before running CI"
echo "       Run ci/lint.sh to run the linter!"
echo "           - The Linting Fairy"
echo " ============================================"
echo
