#!/usr/bin/env bash
set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

if [[ -z "${BUILDKITE-}" ]]; then
  # Local workstations
  ci/bootstrap.sh
  exit 0
fi
if [[ "${BUILDKITE_AGENT_META_DATA_QUEUE}" != "trigger-pipelines" ]] && [[ "${BUILDKITE_AGENT_META_DATA_OS}" == "windows" ]]; then
  ci/bootstrap.sh
fi
